name = "Fabric Server Performance"
author = "Diamond Drake Ventures, LLC"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e89eae08041cdf1cbce2595ddce0f087a3d290988ef354ad5f2345248a02c05"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
