name = "Fabric Server Performance"
author = "Diamond Drake Ventures, LLC"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59ba89ca03be439effc11ae023b6861a51df160b63925bc3269791ae12f3bac7"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
