name = "Fabric Server Performance"
author = "Diamond Drake Ventures, LLC"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e88d23e5671f2b5607cccb687d941d51a11e1257d264b23d9abbca29250771b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
